# Generated by Django 3.2.7 on 2022-11-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
