# Generated by Django 3.2.7 on 2023-02-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0002_alter_assignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resubmissions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='show_target_steps',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proofline',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proofline',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
