# Generated by Django 3.2.7 on 2023-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0002_alter_assignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
