# Generated by Django 3.2.7 on 2023-03-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0003_auto_20230216_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='disproof_string',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
