# Generated by Django 3.2.7 on 2023-02-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0005_auto_20230225_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proof',
            old_name='lemma_allowed',
            new_name='lemmas_allowed',
        ),
    ]
