# Generated by Django 3.2.7 on 2023-03-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0006_rename_lemma_allowed_proof_lemmas_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='lemmas_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
