# Generated by Django 3.2.7 on 2023-03-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0003_auto_20230216_1846'),
        ('proofchecker', '0007_problem_lemmas_allowed'),
    ]

    operations = [
    ]
