# Generated by Django 3.2.7 on 2023-03-07 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0004_proof_disproof_string'),
        ('proofchecker', '0007_problem_lemmas_allowed'),
    ]

    operations = [
    ]
