# Generated by Django 3.2.7 on 2023-03-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0008_merge_20230307_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='disproof_string',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
