# Generated by Django 3.2.7 on 2023-03-08 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0008_merge_20230307_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='lemmas_allowed',
        ),
        migrations.RemoveField(
            model_name='proof',
            name='lemmas_allowed',
        ),
    ]
