# Generated by Django 3.2.7 on 2023-03-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0008_merge_20230307_1806'),
        ('proofchecker', '0008_merge_20230307_1825'),
    ]

    operations = [
    ]
