# Generated by Django 3.2.7 on 2023-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0008_merge_20230307_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
