# Generated by Django 3.2.7 on 2023-07-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0009_alter_proof_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.IntegerField(blank=True, null=True)),
                ('response_msg', models.CharField(default='', max_length=500)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proofchecker.proof')),
            ],
        ),
    ]
