# Generated by Django 3.2.7 on 2023-08-02 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proofchecker', '0010_responsetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetracker',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proofchecker.user'),
            preserve_default=False,
        ),
    ]
