# Generated by Django 3.2.7 on 2022-10-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('proofchecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdelay',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proofchecker.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentdelay',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proofchecker.student'),
        ),
    ]
